name: Publish Package to npmjs

on:
  release:
    types: [published]
  workflow_dispatch: # 👈 allows you to trigger manually from the Actions tab

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Tailwind
        run: npm run tailwind

      - name: build frontend
        run: node ./build

      - name: Dry run publish with provenance
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
